// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skmhyvqlbxhsorulkfns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrbWh5dnFsYnhoc29ydWxrZm5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQxODQxNTgsImV4cCI6MjA3OTc2MDE1OH0.0px1LhYPc3zSJ2eO42QULsI7xPm5S_I2KPWwSd84KGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});